# Generated by Django 4.2.3 on 2023-11-21 09:50

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_name', models.CharField(max_length=50)),
                ('contact_details', models.TextField(max_length=50)),
                ('vendor_address', models.TextField(max_length=50)),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('on_time_delivery_rate', models.FloatField(max_length=50)),
                ('quality_rating_avg', models.FloatField(max_length=50)),
                ('average_response_time', models.FloatField(max_length=50)),
                ('fulfillment_rate', models.FloatField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', jsonfield.fields.JSONField()),
                ('quantity', models.IntegerField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('quality_rating', models.FloatField(max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField(null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(max_length=50)),
                ('quality_rating_avg', models.FloatField(max_length=50)),
                ('average_response_time', models.FloatField(max_length=50)),
                ('fulfillment_rate', models.FloatField(max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendor')),
            ],
        ),
    ]
