# Generated by Django 4.2.3 on 2023-11-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_purchase_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='quality_rating',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfillment_rate',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='on_time_delivery_rate',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='quality_rating_avg',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
