# Generated by Django 4.2.3 on 2023-11-21 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_purchase_order_quality_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='po_number',
            field=models.CharField(default=uuid.uuid4, max_length=50, unique=True),
        ),
    ]
