# Generated by Django 4.2.3 on 2023-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_purchase_order_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
