# Generated by Django 4.2.3 on 2023-11-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_purchase_order_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='average_response_time',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='fulfillment_rate',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='on_time_delivery_rate',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='quality_rating_avg',
            field=models.FloatField(max_length=50, null=True),
        ),
    ]
